version: '3.5'

networks:
    appnet:
        driver: bridge

services:
    webapp:
        image: webrtc
        ports:
            - "8000:8000"
        networks:
            - appnet
        volumes:
            -/home/dell/Desktop/teams_clone/Video-conferencing-too-using-WebRTC:/home

    redis:
        image: redis:5
        networks:
            - appnet
