version: '3.5'

networks:
    appnet:
        driver: bridge

services:
    webapp:
        image: webrtc
        ports:
            - "8000:8000"
        networks:
            - appnet
        volumes:
            - /home/naman/code/Video-conferencing-too-using-WebRTC/:/home

    redis:
        image: redis:5
        networks:
            - appnet
