# Generated by Django 2.2.12 on 2021-06-25 12:48

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=200)),
                ('data_formed', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name=django.contrib.auth.models.User)),
                ('team_id', models.IntegerField()),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
