# Generated by Django 2.2.12 on 2021-06-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_conferencing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_team',
            old_name='username',
            new_name='user_name',
        ),
    ]
