# Generated by Django 2.2.12 on 2021-06-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_conferencing', '0002_auto_20210625_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='user_team',
            name='team_name',
            field=models.CharField(default='demo', max_length=200),
        ),
    ]
