# Generated by Django 2.2.12 on 2021-06-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_conferencing', '0003_auto_20210625_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_formed', models.DateField(auto_now=True)),
            ],
        ),
    ]
